### ISSUE TITLE
程式碼裡面有沒有解掉的 merge conflict

### ISSUE THREAD

**Issue by fntsrlike** [MinecraftSnowServer/auth_minecraft#1]
程式碼裡面有沒有解掉的 merge conflict，如下：

- https://github.com/MinecraftSnowServer/auth_minecraft/blob/master/auth.php#L3
- https://github.com/MinecraftSnowServer/auth_minecraft/blob/master/plugin.info.txt#L3

**Comment by sntc06** [comment]
Sorry, fixed.
